### ISSUE TITLE
octomap include dirs not included

### ISSUE THREAD

**Issue by wjwwood** [moveit/geometric_shapes#12]
`octomap` is `find_package`'ed, and the `OCTOMAP_INCLUDE_DIRS` are exported in the `catkin_package` call, but they are never passed to `include_directories`:

https://github.com/ros-planning/geometric_shapes/blob/hydro-devel/CMakeLists.txt#L38

This causes a build failure on a truly isolated caktin workspace build.

**Comment by wjwwood** [comment]
@isucan Thanks.

**Comment by dirk-thomas** [comment]
This patch needs to be released.
