### ISSUE TITLE
Release in ROS2 Eloquent?

### ISSUE THREAD

**Issue by guru-florida** [moveit/geometric_shapes#132]
Hi. I was surprised to see this missing in ROS2 Eloquent, but apparently is available in Dashing. Is there plans to include it again?

**Comment by tylerjw** [comment]
https://index.ros.org/p/geometric_shapes/

It looks like we have a dashing-devel branch but not a dashing release yet.  This might be because for now moveit2 is depending on this as a source dependency.  It seems like it would be worthwile to release this for dashing/eloquent/foxy.

**Comment by tylerjw** [comment]
Closing because I believe we are targeting only Foxy for ros2.
