### ISSUE TITLE
add so versions?

### ISSUE THREAD

**Issue by simonschmeisser** [moveit/geometric_shapes#146]
As discussed in https://github.com/ros-planning/geometric_shapes/commit/ed4cf1339cf3765ae9ffa6e6fd111a4e342c5fa2#r38768115  adding so-versions would add some safety and help discover issues on binary incompatibility early on.

If I recall correctly there were some issues that bloom cannot actually pass on this information to Debians but at least the software would not start instead of later crashing unexpectedly ...

**Comment by v4hn** [comment]
File a pull-request. I'm in favor of adding it.
The biggest discussion is whether we want to bump the SONAME only on ABI changes or with every release.

**Comment by rhaschke** [comment]
Addressed via #157 in Noetic.
