### ISSUE TITLE
Update CMakeLists.txt to find eigen in indigo

### ISSUE THREAD

**Issue by tfoote** [moveit/geometric_shapes#17]
The FindEigen is in cmake_modules now. 

You need to call find_package(Eigen REQUIRED) after find packaging find_package(catkin COMPONENTS cmake_modules) 

And cmake_modules needs to be a build_depend. 

This sort of patch: https://github.com/ros-visualization/rviz/pull/727

**Comment by dirk-thomas** [comment]
Fixed in 3fbea120f7e4008ebc1516a39b70ba5baf94e321
