### ISSUE TITLE
Is not building in release on trusty/indigo

### ISSUE THREAD

**Issue by mikeferguson** [moveit/geometric_shapes#19]
The configuration on the buildfarm inserts "-DCMAKE_BUILD_TYPE=None", which was not the case in hydro, and which causes https://github.com/ros-planning/geometric_shapes/blob/hydro-devel/CMakeLists.txt#L7 not to be set to Release.

This causes major issues when doing "mergeVertices" in the startup of MoveIt. What normally takes about 3 seconds, suddenly takes over 6 minutes.

It appears that -DCMAKE_BUILD_TYPE=None comes from dh_make? I'm not entirely sure the proper way to fix this. @wjwwood @tfoote do you guys have any input on this from the buildfarm side?

**Comment by tfoote** [comment]
I thiink ros-infrastructure/buildfarm#197 is the root of this.

**Comment by mikeferguson** [comment]
Just needs to be re-released using latest bloom.
