### ISSUE TITLE
CI build jobs not running on Foxy

### ISSUE THREAD

**Issue by henningkayser** [moveit/geometric_shapes#207]
Looks like the build jobs haven't been triggered on the `foxy` branch since https://github.com/ros-planning/geometric_shapes/commit/b4df18c8203a1845fee64bd4b7736304c825104d. At least GitHub doesn't show the build results any more, and I can't find the job runs in the "Actions" panel.

**Comment by vatanaksoytezer** [comment]
Closed by #208.
