### ISSUE TITLE
New Release for Rolling / Jammy

### ISSUE THREAD

**Issue by vatanaksoytezer** [moveit/geometric_shapes#216]
geometric_shapes has been failing in buildfarm since the transition into Jammy. #215 fixes it and after that gets merged we need a new release.

**Comment by DLu** [comment]
@henningkayser It looks like this was merged and you created a new release but did not bloom it. Any reason not to at this point?

**Comment by JafarAbdi** [comment]
> @henningkayser It looks like this was merged and you created a new release but did not bloom it. Any reason not to at this point?

I'm blooming it now

**Comment by JafarAbdi** [comment]
See https://github.com/ros/rosdistro/pull/32678
