### ISSUE TITLE
ROS 1 releases

### ISSUE THREAD

**Issue by peci1** [moveit/geometric_shapes#227]
Both Melodic and Noetic haven't seen a release for over a year. There were a few new things merged in in the meantime. @rhaschke or @tylerjw can I ask you to do a release? Especially Melodic's time is getting short before the EOL...

**Comment by peci1** [comment]
@rhaschke @tylerjw tick tock, one more Melodic Sync has slipped through... Only 2 remaining. Could you please have a look at preparing new ROS 1 releases?

**Comment by rhaschke** [comment]
I will do a release now. Sorry for the delay. I guess the current melodic-devel branch is stable on your side, isn't it?

**Comment by peci1** [comment]
Thanks! Yes, Melodic has everything merged in and should work.

A quick local test says:

    Summary: 194 tests, 0 errors, 0 failures, 0 skipped

**Comment by rhaschke** [comment]
Melodic: https://github.com/ros/rosdistro/pull/36663
Noetic: https://github.com/ros/rosdistro/pull/36664
