### ISSUE TITLE
Release into ROS Jade

### ISSUE THREAD

**Issue by mikeferguson** [moveit/geometric_shapes#27]
Before release, want to:
- [ ] test and pull other changes from https://github.com/ros-planning/geometric_shapes/pull/25 into indigo-devel

Blocking upstream dependencies:
- [x] eigen_stl_containers
- [x] octomap
- [x] [random_numbers](https://github.com/ros-planning/random_numbers/issues/9#issuecomment-94998694)
- [x] resource_retriever
- [x] shape_tools

**Comment by vrabaud** [comment]
@isucan, stop getting married and release that ! :)

**Comment by DLu** [comment]
I was taking a look at releasing the robot_model stack (of which resource_retriever is a part) and collada_urdf (also in robot_model) depends on geometric_shapes. How should I proceed? Just release resource_retriever?

**Comment by mikeferguson** [comment]
Wow -- circular depends between geometric_shapes and robot_model -- I totally did not see that. Checking git-blame on the rosdistro, resource_retriever has apparently been released separately from everything else in the robot_model repo.

The GBP for resource_retriever is here: https://github.com/ros-gbp/resource_retriever-release. Then (Presumably after geometric_shapes was released), the other packages of robot_model got released here: https://github.com/ros-gbp/robot_model-release.

Presumably you should release resource_retriever the same way? @wjwwood It looks like you might have been involved in the robot model releasing for indigo -- any comments on the above?

**Comment by wjwwood** [comment]
Looks like I just did a version bump, @isucan did the original release. It looks like he released `resource_retriever` only in the first gbp you linked using an ignore file, then released the rest of `robot_model` using an ignore file to skip `resource_retriever`. The right thing to do here is to move `resource_retriever` to its own repository, but failing that a similar maneuver could be used to release it as is into jade.

**Comment by isucan** [comment]
@wjwwood is correct - sorry for being late to this and being lazy about the split. But yes, the repo should ideally be split.

**Comment by DLu** [comment]
Is there an easy tool for splitting the repo? (i.e. not just command lines, I can do that)

I presume it would remain in the ros organization as well.

**Comment by wjwwood** [comment]
> Is there an easy tool for splitting the repo? (i.e. not just command lines, I can do that)

Not to my knowledge, it's mostly a git (or VCS specific) set of operations. A guide would be good, but unfortunately I think that having a tool that "just does it" would probably be dangerous if used incorrectly.

**Comment by scpeters** [comment]
+1, this is blocking `gazebo_ros_pkgs` among other things

**Comment by wjwwood** [comment]
Ok, I've moved `resource_retriever` to it's own repository:

https://github.com/ros/resource_retriever.git

and fixed up the indigo release repositories as needed. It was pretty easy since @isucan had already made two release repositories. Here is the pr for the updated release of `resource_retriever` into indigo:

https://github.com/ros/rosdistro/pull/8025

I'll release the Jade versions next.

**Comment by wjwwood** [comment]
Jade release: https://github.com/ros/rosdistro/pull/8026

**Comment by wjwwood** [comment]
I poked `random_numbers`:

https://github.com/ros-planning/random_numbers/issues/9#issuecomment-94998694

and `octomap`:

https://github.com/OctoMap/octomap/issues/80#issuecomment-94994804

Hopefully we can get the ball rolling on this package and all of `robot_model` tomorrow.

**Comment by wjwwood** [comment]
Octomap: https://github.com/ros/rosdistro/pull/8075 :fireworks:

**Comment by wjwwood** [comment]
@mikeferguson I've poked @davetcoleman about either releasing `random_numbers` or giving me the go ahead to do it myself. After that the only thing blocking a Jade release is your mention of #25. Is it important to get that in the first release for Jade?

**Comment by mikeferguson** [comment]
@wjwwood if we release from the indigo-devel branch, it is not important -- basically I didn't want to fork until after that PR was merged.

**Comment by mikeferguson** [comment]
I'll watch for random_numbers on the rosdistro and then release this as soon as that comes through

**Comment by wjwwood** [comment]
Thanks.

**Comment by scpeters** [comment]
I was getting a build failure on utopic without the following:

```
diff --git a/package.xml b/package.xml
index d9b2c0b..ee8191d 100644
--- a/package.xml
+++ b/package.xml
@@ -36,5 +36,6 @@
   <run_depend>random_numbers</run_depend>
   <run_depend>eigen_stl_containers</run_depend>
   <run_depend>resource_retriever</run_depend>
+  <run_depend>visualization_msgs</run_depend>

 </package>
```

This is addressed by #32. Will #32 be merged before the release?

**Comment by scpeters** [comment]
I just made #33 to fix the build if #32 won't be merged before release.

**Comment by wjwwood** [comment]
Ok, `random_numbers` is out: https://github.com/ros/rosdistro/pull/8079 :package: :shipit:

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/8080

**Comment by davetcoleman** [comment]
Great, thanks guys!

on the note of releasing MoveIt! - I'm buried in preparing for the Amazon Picking Challenge so I'm not sure how much help I can provide
