### ISSUE TITLE
problem with either mesh loading or constructMarkerFromShape

### ISSUE THREAD

**Issue by egiljones** [moveit/geometric_shapes#4]
I've recently been trying to create markers from mesh objects, and something is badly wrong.  At this point I am unsure whether the problem is in loading the mesh from the resource in the marker generating code.  In either case, the version of the constructMarkerFromShape that uses triangles doesn't show anything in Rviz, and the line one is garbled, as shown in this image.  It looks to me like maybe the triangles are associated with incorrect vertices.  I will attempt to attach code to this that will help reproduce the problem.  The image shows the results of trying to visualize the base_link of the pr2.

![rviz_bad_base_link](https://f.cloud.github.com/assets/1111454/562964/4771cf54-c4bb-11e2-93c8-3cd65a9b8edc.png)

**Comment by isucan** [comment]
It turns out it was actually a problem in the shape_tools lib, in constructMarkerFromShape; version 0.2.1 (released) fixes the issue.
