### ISSUE TITLE
[Indigo] Release 0.4.5

### ISSUE THREAD

**Issue by 130s** [moveit/geometric_shapes#62]
Already [tagged](https://github.com/ros-planning/geometric_shapes/releases/tag/0.4.5).

Release for Indigo isn't urgent so I'll wait to make a release for https://github.com/ros-infrastructure/ros_buildfarm/issues/347 to be resolved.

**Comment by 130s** [comment]
> Release for Indigo isn't urgent

Please inform if this is not true.

**Comment by rhaschke** [comment]
That's true.

**Comment by davetcoleman** [comment]
can this be closed? seems so

**Comment by 130s** [comment]
This still requires a new release, which I'll work on now.

**Comment by 130s** [comment]
I https://github.com/ros/rosdistro/pull/14510
J https://github.com/ros/rosdistro/pull/14511
