### ISSUE TITLE
Broken box-ray intersection

### ISSUE THREAD

**Issue by LeroyR** [moveit/geometric_shapes#68]
Had some cases where the ray/box intersection was broken.

#67

**Comment by davetcoleman** [comment]
This is confusing how you just have a single number for the description, can you please elaborate?

**Comment by LeroyR** [comment]
#67 is a link to the pull request which shows that raytracing is currently broken
`https://github.com/ros-planning/geometric_shapes/pull/67`

**Comment by LeroyR** [comment]
Again,

TEST(BoxRayIntersection, BrokenRay2)

 box (x=0.2)
 pose x=0.45 
-> box X between 0.25 and 0.65 
with ray from x=0 and direction x=0 should not intersect.

EXPECT_FALSE(intersect)

Results in

[  FAILED  ] BoxRayIntersection.BrokenRay2

**Comment by rhaschke** [comment]
Closed via #73
