### ISSUE TITLE
createMeshFromResource crashes with inventor stl files

### ISSUE THREAD

**Issue by broesdecat** [moveit/geometric_shapes#70]
### Description
Calling createMeshFromResource with an stl mesh exported from Inventor 2018, the program crashes on a memory corruption. Call stack below.

Workaround 1: open the inventor stl file in meshlab (no issue there) and export is as-is as an stl. Calling createMeshFromResource on the resulting stl file works fine.
Workaround 2:  .obj files exported from Inventor are working fine.

The STL files are in attachment, both are binary.

Probably an issue in assimp, but I will leave that to you to log on their repo.

### Your environment
- ROS Distro: Indigo
- OS Version: ros:indigo docker container (aka Ubuntu 14.04)
- Binary build 0.7.11-0trusty-20170621-105324-0800

### Debug info
Actual crash: `malloc(): memory corruption: 0x00000000013f5390`
Stacktrace:
```...
#5  0x00007fe89d6abae0 in __GI___libc_malloc (bytes=2920) at malloc.c:2893
#6  0x00007fe89dc66dad in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fe89dc66ea9 in operator new[](unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f8419983e6b in ?? () from /usr/lib/libassimp.so.3
#9  0x00007f84197b49f6 in ?? () from /usr/lib/libassimp.so.3
#10 0x00007fe89a4aa2c3 in Assimp::Importer::ReadFile(char const*, unsigned int) () from /usr/lib/libassimp.so.3
#11 0x00007fe89a4acfdd in Assimp::Importer::ReadFileFromMemory
#12 0x00007fe89e6bc235 in shapes::createMeshFromBinary
#13 0x00007fe89e6bc5d3 in shapes::createMeshFromResource
#14 0x000000000041cd42 in main ()
```
[mesh.zip](https://github.com/ros-planning/geometric_shapes/files/1251876/mesh.zip)

**Comment by BryceStevenWilley** [comment]
I can't recreate this on 6ae5a0a2922c2183fac1d33cf07a7064ed3c363b, both of the included meshes load fine without crashing. 

I'm going to close this since it's a bit old, but feel free to reopen if you still have this issue.
