### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [moveit/geometric_shapes#78]
All of the dependencies for geometric_shapes are available in Melodic, so it would be great to get this released there.  Thanks in advance!

**Comment by rhaschke** [comment]
@clalancette I would do so. But I don't have permissions for the release repo.

**Comment by rhaschke** [comment]
TODOs for release(s)

- [ ] permission for release repo https://github.com/ros-gbp/geometric_shapes-release.git
- [x] merge #81 to fix #64 
- [x] release 0.5.4 into kinetic
- [x] new melodic-devel branch
- [ ] merge #77 into melodic-devel
- [ ] release 0.6.0 into melodic (API/ABI changes)

**Comment by bmagyar** [comment]
I seem to have push access to the repo so I can do the release once the required merges are done.

**Comment by rhaschke** [comment]
@bmagyar I prepared the release 0.5.4, creating the `changelog` and tag `0.5.4`. If you could `bloom` into Kinetic, that would be great, thanks.
I also suggest to release this version (`0.5.4`) into Melodic for now, so that releasing for ROS Melodic can continue. If #77 is merged, we should release the new version `0.6.0`.

**Comment by bmagyar** [comment]
Thanks! I pushed 0.5.4 to Kinetic, already merged. Ran pre-release tests with dependants for Lunar (took a while!), released there too. Added 0.5.4 to Melodic as well. 

Kinetic and Lunar use `kinetic-devel` while the Melodic release already uses `melodic-devel` for devel branch. We should be good to move on with merges and newer versions soon.

**Comment by BryceStevenWilley** [comment]
Closing this, as we've released.
